### ISSUE TITLE
Don't share caches between different jobs by default

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/cargo-cache#22]
Consider this scenario:

You have one job which runs `cargo test` and one which runs `cargo check`.
These jobs will need separate compilations, as they run with different profiles.

Right now it can happen that they share a cache: Maybe `cargo check` runs first and then `cargo test` cannot find a cache, but _falls back` to the cache generated by `cargo check`.

This can bloat the cache size, as now the `target` folder is filled with both.
This problem can accumulate as the cache is never cleaned up.

A quick solution would be to remove the last cache key fallback which does not depend on the job ID. Then, the `cargo check` and `cargo test` jobs would never share a cache.

This issue has been discovered via <https://github.com/TheBevyFlock/bevy_quickstart/issues/212>

**Comment by benfrankel** [comment]
I actually wonder if it would be best to fully remove cache fallbacks (if it's not possible to prune the `target/` directory automatically). Even if it's just the `Cargo.toml` file changing multiple times, it could cause cache size ballooning with unused dependencies / versions getting pulled into the new cache, though maybe not as rapidly as fallbacks between different jobs.

Needs some testing and consideration of the tradeoffs to decide, though.

**Comment by TimJentzsch** [comment]
Hmm, definitely needs some testing. Compiling without a cache is definitely taking a long time, but maybe it's worth the saved storage space?

**Comment by benfrankel** [comment]
For some anecdotal data: My jam game just had a failed CI due to the runner running out of storage space. I checked and my caches were all ~3.2GB each. I deleted the saved caches and re-ran the same CI workflow, and the new caches were ~400MB, 400MB, and 1.2GB.

**Comment by mirsella** [comment]
hello !
sorry to bump this old issue.
i agree with this change, but maybe we can do even better and not have to create a different job between cargo check and cargo test ?
because the `Swatinem/rust-cache@v2` action works with both, and both are cached

**Comment by BD103** [comment]
> i agree with this change, but maybe we can do even better and not have to create a different job between cargo check and cargo test ?
> because the `Swatinem/rust-cache@v2` action works with both, and both are cached

I'm not sure I understand. Could you please elaborate what behavior you want? (Perhaps [create a separate issue](https://github.com/Leafwing-Studios/cargo-cache/issues/new)?)

**Comment by mirsella** [comment]
oh my bad, after testing further to recreate the issue, it works now. i think clearing the cached fixed it 🤷 
have a good day !
