### ISSUE TITLE
Cache became invalid with cargo version `1.80.1`

### ISSUE THREAD

**Issue by benfrankel** [Leafwing-Studios/cargo-cache#25]
The cargo version changed, but the commit hash / date did not:
```
cargo 1.80.0 (376290515 2024-07-16)
cargo 1.80.1 (376290515 2024-07-16)
```

Since then, I'm seeing CI runs that consistently hit the cache successfully but then do a full rebuild. I worked around this by manually deleting my cache so that it can be rebuilt.

**Comment by TimJentzsch** [comment]
Nice catch. I thought these would always change together, but apparently not. We probably have to use both `cargo --version` and `rustc --version` together.

**Comment by benfrankel** [comment]
Some more information:

```bash
$ cargo +stable --version
cargo 1.80.0 (376290515 2024-07-16)
$ rustc +stable --version
rustc 1.80.0 (051478957 2024-07-21)

$ rustup update

$ cargo +stable --version
cargo 1.80.1 (376290515 2024-07-16)
$ rustc +stable --version
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

Rust 1.80.1 was released yesterday. Full changelog: https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1801-2024-08-08. This is an example of a release with bug fixes to `rustc` but no changes to `cargo`.

On the other hand, here's an example of a release with a bug fix to `cargo` but no changes to `rustc`: https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1661-2023-01-10.

**Comment by BD103** [comment]
Right now we do the following to extract the version number:

https://github.com/Leafwing-Studios/cargo-cache/blob/9ba9627840c191fc156cb3e76feaf08deb0aa509/action.yml#L82-L84

I think we could either expand the Regex to also capture the official version number (`1.80.1`, `1.72.0-nightly`, etc.), or hash the entire output of `cargo --version` and use that instead.
