### ISSUE TITLE
Duplicate caches with same name

### ISSUE THREAD

**Issue by mnmaita** [Leafwing-Studios/cargo-cache#31]
I'm using this action to cache my dev builds and then reuse them whenever someone pushes a new pull request.

Using `cache-groups` so the same job/s use the same cache. But whenever I'm pushing a new ref and opening a new PR, the action will create a new cache with the exact same name and report there was no cache hit.

Is this intended because it's being triggered from different runs even though it's the same workflow and job doing it?

**Comment by BD103** [comment]
Hi! Unfortunately that is a restriction of Github, not something on our end. Caches created on branches can only be used by their direct children. Please see [this article](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) for more details.

I'm recommend making cached jobs run on push to the main branch. Then, that cache can be used by all pull requests.

**Comment by mnmaita** [comment]
Thanks, this is exactly what I needed to know!
