### ISSUE TITLE
allow changing cache's compression ratio

### ISSUE THREAD

**Issue by mirsella** [Leafwing-Studios/cargo-cache#41]
hello !

for me most of the CI time is now the `Run Leafwing-Studios/cargo-cache@v2.5.0` or `Post Run Leafwing-Studios/cargo-cache@v2.5.0`.
its not a big time, so no big deal, but i would like to optimize this further.
![Image](https://github.com/user-attachments/assets/b4401934-a852-4ec6-b96a-b616d085c6a6)

i guess most of the time is the (un)archiving of the cache (1.7gb here):

![Image](https://github.com/user-attachments/assets/166f3a1a-96ba-42a2-b53f-25222194e227)

github project have a 10gb cache limit, and most project will use only one or two caches. so a option to change the zstd compression ratio, to use more space but be faster, would be useful and be applicable for a lot of user

thanks

**Comment by TimJentzsch** [comment]
Hey there, unfortunately this might not be possible to implement as of now.

We use https://github.com/actions/cache under the hood to create and download the caches and I didn't see any options to configure the caching algorithm or its parameters.

**Comment by mirsella** [comment]
thanks for the answer ! ill see on actions/cache repo if i can find useful things

have a good day
